### ISSUE TITLE
Main site not updated for a couple of weeks

### ISSUE THREAD

**Issue by jimsimonz** [hugoattal/OrbitalMarket#41]
Usually it updates every day, seems stuck

**Comment by hugoattal** [comment]
Ooooh, sorry for this, I'm looking into it...

**Comment by hugoattal** [comment]
Seems like it was a weird encoding error due to some changes in the marketplace. It's fixed, and just I triggered the scrapper, so new products should start filling in. (The whole process takes about ~15 minutes)

This should be fixed for upcoming updates as well (https://github.com/hugoattal/OrbitalMarket/commit/de8b91a48e14ea4ee6461add4932c121202ff91f)
